theme: minima
title: "james bog"
author: james davis
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  a place where i talk about bogs, wetlands, whatnot

# social links
twitter_username: jdavis_tweets # DO NOT include the @ character, or else the build will fail!
github_username:  jdavis-codes # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
